types <- function() {
  c(
    "int",
    "real",
    "vector",
    "simplex",
    "ordered",
    "row_vector",
    "matrix",
    "corr_matrix",
    "cov_matrix",
    "positive_ordered",
    "array",
    "cholesky_factor_cov",
    "cholesky_factor_corr",
    "unit_vector",
    "sum_to_zero_vector",
    "sum_to_zero_matrix"
  )
}
